
server:
  port: 8080

girl:
  cupSize: B
  age: 18
spring:
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
#thymeleaf end

#content: "cupSize: ${cupSize},age: ${age}"
