spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dbgirl
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    spring.jpa.hibernate.naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

    spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect



#server:
#  port: 8080
#
#girl:
#  cupSize: B
#  age: 18
#content: "cupSize: ${cupSize},age: ${age}"
